"""Renamer — dry-run preview, execute (with undo log), and undo.

Templates use the token engine in app.core.naming, e.g.::

    Movie:  {title} ({year})/{titleSort;originalTitle;title} ({year}) [{resolution};{source}]{ext}
    TV ep:  {showTitle}/Season {season}/{showTitle} - {seasonEpisode} - {title}{ext}
    TV show folder: {showTitle} ({year})

Fallback syntax ``{originalTitle;title}`` picks the first non-empty token.
"""
from __future__ import annotations

import json
import os
import shutil
import uuid
from datetime import datetime
from pathlib import Path

from sqlmodel import Session, select

from app.core.naming import apply_template
from app.models.library import Library, LibraryType
from app.models.media import Episode, Movie, TvShow
from app.models.rename_log import RenameLog
from app.schemas import RenamePreviewItem

# Companion file extensions moved alongside the media file during a rename.
# These are the artwork / metadata files generated by the scraper.
_COMPANION_EXTS = {".jpg", ".jpeg", ".png", ".nfo"}


def _is_companion(path: Path) -> bool:
    """True if a file is artwork or NFO that should follow the media file."""
    return path.suffix.lower() in _COMPANION_EXTS


def _move_companions(src_dir: Path, dest_dir: Path) -> list[tuple[str, str]]:
    """Move companion files (poster.jpg, *.nfo, season posters) from src_dir to
    dest_dir. Returns a list of (from, to) pairs for the undo log.

    Only moves files in src_dir itself (not subdirs). Files already present at
    the destination with the same name are left in place (skip, don't clobber).
    """
    if not src_dir.exists() or not src_dir.is_dir():
        return []
    moved: list[tuple[str, str]] = []
    dest_dir.mkdir(parents=True, exist_ok=True)
    for entry in src_dir.iterdir():
        if not entry.is_file() or not _is_companion(entry):
            continue
        target = dest_dir / entry.name
        if target.exists():
            continue  # don't overwrite an existing companion at destination
        try:
            os.rename(entry, target)
            moved.append((str(entry), str(target)))
        except OSError:
            pass
    return moved


def _row_context(row, *, show: TvShow | None = None, ext: str | None = None) -> dict:
    """Build a flat context dict for the naming engine from a media row."""
    ctx = {k: getattr(row, k, None) for k in (
        "title", "original_title", "year", "tmdb_id", "imdb_id", "rating", "votes",
        "genres", "certification", "runtime", "studio", "collection", "language",
        "resolution", "source", "codec", "audio_codec", "audio_channels",
        "release_group", "parsed_title", "parsed_year",
    )}
    # normalize a couple aliases the engine also accepts
    ctx["ext"] = ext
    if show is not None:
        ctx["show_title"] = show.title or show.original_title or show.parsed_title
        # episodes may want the show's year/ids if their own are empty
        ctx.setdefault("year", row.year or show.year)
    # season/episode for episodes
    ctx["season"] = getattr(row, "season_number", None)
    ctx["episode"] = getattr(row, "episode_number", None)
    return ctx


def _split_rel(template: str) -> str:
    """Everything after the last '/' is the filename portion."""
    return template


def _template_has_dir(template: str) -> bool:
    return "/" in template


def preview_movies(session: Session, library: Library, template: str | None = None) -> list[RenamePreviewItem]:
    template = template or library.naming_template
    movies = session.exec(select(Movie).where(Movie.library_id == library.id)).all()
    items: list[RenamePreviewItem] = []
    for m in movies:
        src = Path(m.file_path)
        if not src.exists():
            continue
        ctx = _row_context(m, ext=src.suffix)
        target_rel = apply_template(template, ctx)
        dest = _resolve_movie_dest(src, target_rel)
        conflict = dest.exists() and dest.resolve() != src.resolve()
        items.append(RenamePreviewItem(
            media_id=m.id, media_type="movie",
            from_path=str(src), to_path=str(dest), conflict=conflict,
        ))
    return items


def preview_episodes(session: Session, library: Library, template: str | None = None) -> list[RenamePreviewItem]:
    template = template or library.naming_template
    show_template = library.tv_show_template or "{showTitle} ({year})"
    episodes = session.exec(select(Episode).where(Episode.library_id == library.id)).all()
    items: list[RenamePreviewItem] = []
    for ep in episodes:
        src = Path(ep.file_path)
        if not src.exists():
            continue
        show = session.get(TvShow, ep.show_id)
        ctx = _row_context(ep, show=show, ext=src.suffix)
        target_rel = apply_template(template, ctx)
        dest, to_show_folder, to_season_folder = _resolve_episode_dest(
            src, target_rel, show, ep.season_number, show_template, ctx
        )
        conflict = dest.exists() and dest.resolve() != src.resolve()
        items.append(RenamePreviewItem(
            media_id=ep.id, media_type="episode",
            from_path=str(src), to_path=str(dest), conflict=conflict,
            show_id=ep.show_id,
            show_title=_show_display_name(show),
            season_number=ep.season_number,
            to_show_folder=to_show_folder,
            to_season_folder=to_season_folder,
        ))
    return items


def _show_display_name(show: TvShow | None) -> str | None:
    """Best-effort human name for a show: title -> original_title -> parsed_title -> folder basename."""
    if show is None:
        return None
    for attr in ("title", "original_title", "parsed_title"):
        v = getattr(show, attr, None)
        if v:
            return v
    # fall back to the folder name
    try:
        fp = getattr(show, "folder_path", None)
        if fp:
            return Path(fp).name
    except Exception:
        pass
    return None


def _resolve_movie_dest(src: Path, target_rel: str) -> Path:
    """Compute the destination for a movie file.

    If the template contains a '/', the leading segment(s) define a subfolder
    *under the existing movie's own folder* (not the library root), so files
    stay grouped. Without '/', the file just changes its name in place.
    """
    if _template_has_dir(target_rel):
        # Keep within the movie's folder (its parent) — group artwork + nfo together.
        return src.parent / target_rel
    return src.parent / target_rel


def _resolve_episode_dest(
    src: Path,
    target_rel: str,
    show: TvShow | None,
    season_num,
    show_template: str,
    ctx: dict,
) -> tuple[Path, str | None, str | None]:
    """Resolve an episode's destination and the new show/season folder names.

    The episode template normally renders as ``{showTitle}/Season {season}/file``.
    We anchor the FULL path under the TV root (the show folder's parent), so the
    renamed show folder + season folder + filename are all reflected in to_path.

    Returns (dest, to_show_folder, to_season_folder). The folder names are the
    new names for the tree's group rows; they may equal the originals.
    """
    parts = Path(target_rel).parts
    # Determine the TV root: the show folder's parent (e.g. .../TV given .../TV/Show).
    show_folder = Path(show.folder_path) if show is not None else src.parent
    tv_root = show_folder.parent

    # New show folder name: prefer the explicit tv_show_template, else the first
    # segment of the episode template (which is usually {showTitle}).
    to_show_name = apply_template(show_template, ctx).strip() if ctx else None
    if not to_show_name:
        to_show_name = parts[0] if parts else show_folder.name
    to_show_folder = to_show_name or None

    # New season folder name: the middle segment of the rendered template, if any.
    to_season_folder = parts[1] if len(parts) >= 3 else None

    # Reconstruct dest anchored at the TV root, keeping the (possibly renamed)
    # show + season + filename structure from the rendered template.
    if len(parts) >= 2:
        # Replace the template's show segment with the canonical show-folder name
        # (so show folder + tv_show_template stay consistent), keep the rest.
        tail = Path(*parts[1:]) if len(parts) > 1 else Path(target_rel)
        dest = tv_root / to_show_name / tail
    else:
        # No directory structure in template → keep file beside the season folder.
        dest = show_folder / target_rel
    return dest, to_show_folder, to_season_folder


def execute(
    session: Session,
    library: Library,
    media_ids: list[int],
    media_type: str,
    template: str | None = None,
) -> tuple[str, int]:
    """Execute rename for selected ids. Returns (batch_id, count_moved)."""
    batch_id = uuid.uuid4().hex[:12]
    moved = 0

    previews = (
        preview_movies(session, library, template)
        if media_type == "movie"
        else preview_episodes(session, library, template)
    )
    by_media = {p.media_id: p for p in previews}

    for mid in media_ids:
        plan = by_media.get(mid)
        if not plan:
            continue
        src = Path(plan.from_path)
        dest = Path(plan.to_path)
        if not src.exists() or dest.exists():
            continue
        try:
            dest.parent.mkdir(parents=True, exist_ok=True)
            os.rename(src, dest)
        except OSError:
            continue

        # Move companion artwork/NFO from the source folder into the dest
        # folder so they follow the media file (scraper drops poster.jpg,
        # fanart.jpg, *.nfo next to the file).
        companions = _move_companions(src.parent, dest.parent)

        # Keep the DB row's stored path valid.
        if media_type == "movie":
            row = session.get(Movie, mid)
        else:
            row = session.get(Episode, mid)
        if row is not None:
            row.file_path = str(dest)
            row.filename = dest.name
            row.updated_at = datetime.utcnow()
            session.add(row)

        session.add(RenameLog(
            library_id=library.id, batch_id=batch_id,
            from_path=plan.from_path, to_path=plan.to_path,
            media_type=media_type, media_id=mid,
            companion_paths=json.dumps(companions) if companions else None,
        ))
        moved += 1

    # TV: prune now-empty season/show folders left behind, and refresh the show's
    # folder_path in the DB so a later rescan / undo stays consistent.
    if media_type != "movie":
        _cleanup_tv_folders(session, moved_previews=[
            (by_media[mid], Path(by_media[mid].from_path), Path(by_media[mid].to_path))
            for mid in media_ids if mid in by_media
        ])

    session.commit()
    return batch_id, moved


def _cleanup_tv_folders(session: Session, moved_previews: list[tuple]) -> None:
    """After moving episode files, delete emptied season/show folders and point
    each show's folder_path at its new location (deduplicated by show_id)."""
    # Map show_id -> (old show folder, new show folder) from the moved episodes.
    show_moves: dict[int, tuple[Path, Path]] = {}
    for plan, _src, dest in moved_previews:
        if plan.show_id is None:
            continue
        old_show = Path(plan.from_path).parent
        # src is .../Show/Season xx/file  → show folder is two levels up
        try:
            old_show = Path(plan.from_path).parents[1]
        except IndexError:
            old_show = Path(plan.from_path).parent
        new_show = dest.parents[1] if len(dest.parents) > 1 else dest.parent
        show_moves[plan.show_id] = (old_show, new_show)

    for show_id, (old_show, new_show) in show_moves.items():
        # update DB folder_path to the new location
        show = session.get(TvShow, show_id)
        if show is not None and str(new_show) != show.folder_path:
            show.folder_path = str(new_show)
            show.updated_at = datetime.utcnow()
            session.add(show)
        # remove emptied season folders under the OLD show folder, then the
        # show folder itself if fully empty.
        _prune_empty_dirs(old_show)


def _prune_empty_dirs(root: Path, *, max_depth: int = 3) -> None:
    """Delete leaf directories that are empty, walking bottom-up, stopping at root."""
    if not root.exists() or not root.is_dir():
        return
    for _ in range(max_depth):
        emptied = False
        for dirpath, dirnames, filenames in os.walk(root, topdown=False):
            d = Path(dirpath)
            if d == root:
                continue
            if not dirnames and not filenames:
                try:
                    d.rmdir()
                    emptied = True
                except OSError:
                    pass
        if not emptied:
            break
    # finally the show folder itself
    try:
        if root.exists() and root.is_dir() and not any(root.iterdir()):
            root.rmdir()
    except OSError:
        pass


def undo(session: Session, batch_id: str | None = None) -> int:
    """Revert a rename batch (latest if batch_id is None). Returns count reverted."""
    if batch_id is None:
        latest = session.exec(
            select(RenameLog).where(RenameLog.reversed == False).order_by(RenameLog.created_at.desc())
        ).first()
        if not latest:
            return 0
        batch_id = latest.batch_id

    logs = session.exec(select(RenameLog).where(RenameLog.batch_id == batch_id, RenameLog.reversed == False)).all()
    reverted = 0
    # reverse the move, and patch DB paths back.
    moved_back_paths: list[Path] = []
    for log in logs:
        src = Path(log.to_path)
        dest = Path(log.from_path)
        moved_back = False
        try:
            if src.exists() and not dest.exists():
                dest.parent.mkdir(parents=True, exist_ok=True)
                os.rename(src, dest)
                moved_back = True
                reverted += 1
        except OSError:
            moved_back = False
        finally:
            if moved_back:
                _restore_db_path(session, log)
                moved_back_paths.append(src)
                # Restore companion files (artwork/NFO) back to their origin.
                _restore_companions(log)
            log.reversed = True
            session.add(log)

    # TV undo: also restore folder_path and prune the now-empty new folders.
    if logs and logs[0].media_type != "movie":
        _undo_tv_folders(session, logs, moved_back_paths)

    session.commit()
    return reverted


def _undo_tv_folders(session: Session, logs: list[RenameLog], moved_back_src: list[Path]) -> None:
    """Restore show folder_path to the originals and drop emptied new folders."""
    # The "new" (to-be-removed) show folders are the parents of moved-back srcs.
    new_show_dirs: set[Path] = set()
    show_ids_to_restore: dict[int, str] = {}
    for log, src in zip(logs, moved_back_src):
        try:
            new_show_dirs.add(src.parents[1])
        except IndexError:
            new_show_dirs.add(src.parent)
        # original show folder = from_path's show dir (.../Show/Season xx/file)
        try:
            orig_show = str(Path(log.from_path).parents[1])
        except IndexError:
            orig_show = str(Path(log.from_path).parent)
        # find the show via the episode row
        if log.media_id is not None:
            ep = session.get(Episode, log.media_id)
            if ep is not None:
                show_ids_to_restore[ep.show_id] = orig_show
    for show_id, orig_folder in show_ids_to_restore.items():
        show = session.get(TvShow, show_id)
        if show is not None and show.folder_path != orig_folder:
            show.folder_path = orig_folder
            show.updated_at = datetime.utcnow()
            session.add(show)
    for d in new_show_dirs:
        _prune_empty_dirs(d)


def _restore_db_path(session: Session, log: RenameLog) -> None:
    """Point the media row back to its original path after undo."""
    Model = Movie if log.media_type == "movie" else Episode
    if log.media_id is None:
        return
    row = session.get(Model, log.media_id)
    if row is not None:
        row.file_path = log.from_path
        row.filename = Path(log.from_path).name
        session.add(row)


def _restore_companions(log: RenameLog) -> None:
    """Move companion files (artwork/NFO) back to where they came from.

    Reads the companion_paths JSON stored on the log row (list of [from, to]
    pairs) and reverses each move: from the (post-rename) location back to the
    original. Skips files that no longer exist or whose target already exists.
    """
    if not log.companion_paths:
        return
    try:
        pairs = json.loads(log.companion_paths)
    except (json.JSONDecodeError, TypeError):
        return
    for pair in pairs:
        if not (isinstance(pair, (list, tuple)) and len(pair) == 2):
            continue
        cur = Path(pair[1])   # where it was moved TO
        orig = Path(pair[0])  # where it came FROM
        try:
            if cur.exists() and not orig.exists():
                orig.parent.mkdir(parents=True, exist_ok=True)
                os.rename(cur, orig)
        except OSError:
            pass
